receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp/aspire:
    endpoint: "aspire-dashboard:18889"
    tls:
        insecure: true
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
        insecure: true
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp/aspire, otlp/jaeger]
    metrics:
      receivers: [otlp]
      exporters: [debug, otlp/aspire]
    logs:
      receivers: [otlp]
      exporters: [debug, otlp/aspire]
