services:
  collector:
    depends_on:
      - aspire-dashboard
      - jaeger
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.1.0
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true 
    ports:
      - "18888:18888"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"

